### DISCUSSION TITLE
Won't scan PDF

### DISCUSSION THREAD

**Discussion by kirawi** [stumpapp/stump#573] [General]
(I am using Podman)

```yml
services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    # Replace my paths (prior to the colons) with your own
    volumes:
      - /home/stumpapp/.stump:/config
      - /home/stumpapp/media/books:/data
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
      # This `environment` field is optional, remove if you don't need it.
      # I am using it as an example here, but it's actually a default value.
      - STUMP_CONFIG_DIR=/config
    restart: unless-stopped
```

The tree is like so inside /media/books
```
.
└── textbooks
    └── calculus
        └── calc.pdf
```

I create a library for the textbooks/ dir, but scanning will not add the PDF to the library.  I see it in the `files` tab, but it can't be opened from there because of `No associated DB entry found for this file`
