### ISSUE TITLE
[FEATURE] Authenticate via LDAP, OAuth2, SAML etc.

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#246]
### Discussed in https://github.com/stumpapp/stump/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **nk44-official** January 17, 2024</sup>
Hey,

Are there plans to implement LDAP or other SSO Solutions in the future? :)</div>

**Comment by paulcsiki** [comment]
OIDC would fit very nice in my home lab setup.

**Comment by aaronleopold** [comment]
Found this recently, will be a likely candidate for implementation: https://github.com/pfzetto/axum-oidc

**Comment by nk44-official** [comment]
> Found this recently, will be a likely candidate for implementation: https://github.com/pfzetto/axum-oidc

that would be wonderful!

**Comment by aaronleopold** [comment]
For those following this issue, we are getting closer to a point where I can work on this now that #219 is complete. My current **rough** idea is that there would be some new configuration added to define your oidc / sso provider which "unlocks" different authentication endpoints on the API and login methods on the UI. If you have any thoughts on this, please let me know.

Otherwise, stay tuned 🙂

**Comment by nk44-official** [comment]
that sounds awesome!

**Comment by wreid23** [comment]
Please use PocketID as a good easy test subject to connect with once you reach the testing phase not sure where we are at this moment but exciting news this is a very cool project and getting OIDC working is a must nowadays especially with so many good "easy" middlewares today. The code from https://github.com/9p4/jellyfin-plugin-sso might also help give you some good ideas on how to keep it simple as well.

**Comment by b3nd1k** [comment]
Any updates on this?

**Comment by aaronleopold** [comment]
> Any updates on this?

No updates. My time and focus has been absorbed by the massive rewrite effort. Just compare the `experimental` branch with `main` 😅 

I would love contributions if folks want it sooner, otherwise it will come sometime after the rewrite stabilizes a bit

**Comment by aaronleopold** [comment]
> > Any updates on this?
> 
> No updates.

I decided to [work on this a bit](https://github.com/stumpapp/stump/tree/oidc) to better gauge the effort. I've used PocketID for testing (thank you, @wreid23) and so far session-based auth seems functional. There are lots of kinks I would need to work through, and getting this functional using JWTs for the mobile app will be a bit involved, but I'll try and get something out to an `unstable` image by January

**Comment by aaronleopold** [comment]
The foundational work from https://github.com/stumpapp/stump/pull/826 is now available in the `unstable` docker build if anyone interested in this feature is able to give it a spin. I did wind up updating the mobile app to support OIDC which is pretty nice, but until this gets attention and testing in `unstable` the app won't get support until I feel confident enough to promote it to `experimental`.

Until then, you can also find the docs I added for OIDC [right here](https://github.com/stumpapp/stump/blob/unstable/apps/docs/pages/guides/access-control/oidc.mdx)

**Comment by wolsen9** [comment]
I was going to try the unstable brach for OIDC using Authelia, my question is I do not see a OIDC callback URL for Stump?  Something like `https://stump.example.com/oauth2/callback`

**Comment by aaronleopold** [comment]
> I was going to try the unstable brach for OIDC using Authelia, my question is I do not see a OIDC callback URL for Stump? Something like `https://stump.example.com/oauth2/callback`

Ahhh yeah I totally missed that in the docs, I'll be sure to add it. It should be:

```
https://stump.example.com/api/v2/auth/oidc/callback
```

**Comment by wolsen9** [comment]
I do not have OIDC with Authelia working yet, running into some issue but also out of time for now, will circle back.  Stump Error:
```
 2025-12-01T16:06:04.383510Z ERROR stump_server::routers::api::v2::oidc: Failed to exchange code for claims: OIDCMissingEmail
    at apps/server/src/routers/api/v2/oidc.rs:199
    in tower_http::trace::make_span::request with method: GET, uri: /api/v2/auth/oidc/callback?code=authelia_ac_er-WDcc4nRJpHzrH0UDI-7f37D7jvMIx6aRT9qvGk68.Xiw5o9HqpheVacyuMYQ1FrVUGzPza24wyyXfhW5gSoE&iss=https%3A%2F%2Fauth.example.com&scope=openid+email+profile&state=%7B%22generate_token%22%3Afalse%2C%22redirect_uri%22%3Anull%7D, version: HTTP/1.1

  2025-12-01T16:06:04.383658Z ERROR stump_server::errors: API error response, error: APIErrorResponse { status: 401, message: "Unauthorized" }
    at apps/server/src/errors.rs:323
    in tower_http::trace::make_span::request with method: GET, uri: /api/v2/auth/oidc/callback?code=authelia_ac_er-WDcc4nRJpHzrH0UDI-7f37D7jvMIx6aRT9qvGk68.Xiw5o9HqpheVacyuMYQ1FrVUGzPza24wyyXfhW5gSoE&iss=https%3A%2F%2Fauth.example.com&scope=openid+email+profile&state=%7B%22generate_token%22%3Afalse%2C%22redirect_uri%22%3Anull%7D, version: HTTP/1.1
```

Notes on it, stump configuration: 
```
      - STUMP_OIDC_ENABLED=true
      - STUMP_OIDC_ISSUER_URL=https://auth.example.com    #nothing after
      - STUMP_OIDC_CLIENT_ID=${client_id}
      - STUMP_OIDC_CLIENT_SECRET=${client_secret}
      - STUMP_OIDC_SCOPES=openid,email,profile    #tried defining and not
      - STUMP_OIDC_ALLOW_REGISTRATION=true
      #- STUMP_OIDC_DISABLE_LOCAL_AUTH=false
```

Authelia configuration:
```
      - client_id: ${client_id}
        client_name: 'Stump'
        client_secret: 'supersecret'
        public: false
        redirect_uris:
          - 'https://stump.example.com/api/v2/auth/oidc/callback'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        authorization_policy: 'library_policy'
        consent_mode: 'implicit'
        #pre_configured_consent_duration: ‘2 week’
        require_pkce: false    #tried turn and false
        pkce_challenge_method: ''    #'S256'
        token_endpoint_auth_method: 'client_secret_basic'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
```

**Comment by aaronleopold** [comment]
Thank you, @wolsen9! The error comes from [here](https://github.com/stumpapp/stump/blob/unstable/apps/server/src/config/oidc.rs#L144-L147), if you're curious. The scope configs look correct to me, so not sure why the response is missing it.

I'll try to spin up my own Authelia (thank you for the config to start with 🙏) sometime soon to help figure it out. Ideally at the end of all this, besides a merge to experimental, it would be nice to have small write-ups for a few providers like PocketID, Authelia, etc

**Comment by wolsen9** [comment]
I lied, had more time, but it's working!  Looking back at other Client's I've setup, saw that claims policy's have been used in the past, so I figured - why not, though I certainly do not know what it means for Authelia or Stump.  Thinned out OIDC provide section, added the claims policy for stump, it seems to work.

```
identity_providers:
  oidc:
    hmac_secret: 'supersecret1' #non-hashed
    jwks:
    - algorithm: 'RS256'
      use: 'sig'
      ## Required Private Key in PEM DER form. non-hashed
      key: "-----BEGIN RSA PRIVATE KEY——-“
    claims_policies:
      stump_policy:
        id_token: ['email', 'name']
    lifespans:
      access_token: '1 hour'
      authorize_code: '1 minute'
      id_token: '1 hour'
      refresh_token: '90 minutes'
    clients:
      - client_id: 'Stump_OIDC' #'OIDC_CLIENT_ID'
        client_name: 'Stump'
        client_secret: 'supersecret2' #hashed
        redirect_uris:
          - 'https://stump.example.com/api/v2/auth/oidc/callback'
        authorization_policy: 'one_factor'
        claims_policy: 'stump_policy'
        consent_mode: 'implicit'
```
