### ISSUE TITLE
[BUG] Mark As Read "Invalid Date"

### ISSUE THREAD

**Issue by TheRouce** [stumpapp/stump#260]
**Describe the bug**
When marking any book as read it displays "Completed on Invalid Date"

**To Reproduce**

1. Start docker instance on RPI
2. Click on any book
3. Click "Mark As Read"
4. See bug

**Expected behavior**
Presumably it would show when it was read.

**Screenshots**
![image](https://github.com/stumpapp/stump/assets/40551268/6153cdf6-ea72-41f0-bb6b-f7aa56581cbe)
![Peek 2024-02-03 15-51](https://github.com/stumpapp/stump/assets/40551268/efd47d66-ce1c-42c8-a1db-7fe5b7a82237)

**Additional context**
OS: Alpine Linux v3.19
Host: Raspberry Pi 4 Model B Rev 1.2 
Kernel: 6.6.12-0-rpi 

docker-compose.yml:
```
version: '3.3'
services:
  stump:
    image: aaronleopold/stump:nightly
    container_name: stump
    volumes:
      - /data/Books/stump/config:/config
      - /data/Books/data:/data
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
```
Running "date" inside the container shows that chrony is working:
```
root@a2b79a7b0311:/app# date
Sat Feb  3 20:54:08 UTC 2024
```
