### ISSUE TITLE
[BUG] Cannot delete a user from the list

### ISSUE THREAD

**Issue by gpatruno** [stumpapp/stump#372]
**Describe the bug**
I'm trying to delete a user I've created. When I look at the documentation, it says : 
To delete a user, navigate to /settings/users in your browser. Locate the Users table and click the action menu button (three dots) for the user you wish to delete.
However, I can't find the menu button for deleting a user. 
I used the Docker image aaronleopold/stump:nightly, aaronleopold/stump:0.0.4 and aaronleopold/stump:0.0.3 and no one of these versions have a menu button in the users table.

**To Reproduce**
As administrator, create a user with rights. Still as admin, go to /settings/users to display the list of users. 

As Server Owner:
1. Go to '/settings/users' 
2. Click on 'Create User' 
3. reload the page '/settings/users'
4. the new user appears in the list but without a menu

**Expected behavior**
I don't know if this feature is currently under development. I assume it should be present as it is documented. 
Maybe I'm using the wrong Docker image or a wrong config... . 

**Screenshots**
![tableusers](https://github.com/user-attachments/assets/2bd8af2b-7b37-4b3f-a62e-a4c94531791d)

Docker config:
```
services:

  stump:
    image: aaronleopold/stump:nightly
    container_name: stump
    volumes:
      - ./config:/config
      - ./media/books:/data
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - GUID=1000
      - STUMP_CONFIG_DIR=/config
    restart: unless-stopped

volumes:
  stump-volume:
```

**Additional context**
I've tried to use Postman to delete the user with his ID but I can't use the route. This may be a misuse, as I'm not familiar with the language used on the server side. However, I've retrieved the list of users by API with Postman.
