### ISSUE TITLE
[BUG?] very slow in creating library

### ISSUE THREAD

**Issue by Cantello** [stumpapp/stump#427]
**Describe the bug**
When adding a library, the media entities are sometimes added quickly but thumbnails take forever or are not generated at all, sometimes, the entities are not created at all.

**To Reproduce**

1. Start the docker container (on debian 12), docker-compose.yml is below
```
  stump:
    image: aaronleopold/stump
    container_name: stump
    volumes:
      - /opt/stump:/config
      - /mnt/_nfs/Stuff:/data_nfs
      - /tmp:/temporary
    ports:
      - 10801:10801
    environment:
      - STUMP_CONFIG_DIR=/config
      - PUID=1000
      - PGID=1000
      - STUMP_VERBOSITY=2
    restart: unless-stopped
```
2. Initialize server
3. Create library (single folder, 40 .cbz files, series-based, thumbnails enabled with 200x350)
4. Library is either created but thumbnails are not generated (or extremely slow, like 1 per minute), OR
5. Library is not created at all ("No books to display", the series is created but with 0 books in it, the files are there in the files tab within the series)

**Expected behavior**
Library is created with thumbnails

**Screenshots**
<details><summary>Click to expand</summary>

<p>

![2024-08-31 18_08_46-Stump _ Test](https://github.com/user-attachments/assets/fd3918a6-4baa-44ea-9816-41bc3a51c5d3)
![2024-08-31 18_09_03-Stump](https://github.com/user-attachments/assets/44a5d726-461d-40f5-996e-45df00ad4b05)
![2024-08-31 18_07_38-Stump _ Home](https://github.com/user-attachments/assets/228b12a1-25e5-489f-bf14-4700792dbea4)

</p>

</details>

**Desktop (please complete the following information):**
Access on Windows, Vivaldi as browser, stump is hosted on docker on debian 12.

**Additional context**
Log file here (maybe not enough and/or too chatty, was using verbosity 3):

https://logpaste.com/6lqmqRvU

The container stats are also interesting, nearly no CPU usage (1-2%) but huge memory usage (2.5GB after 15 minutes and rising).
