### ISSUE TITLE
[FEATURE] Docker user settings

### ISSUE THREAD

**Issue by Silther** [stumpapp/stump#539]
**Is your feature request related to a problem?**

Docker allows to set the user directly without the environment, which is preferable. As it makes it more secure and less complex. 

**Describe the solution you'd like**
```
services:
  stump:
    container_name: stump
    image: aaronleopold/stump:latest
    restart: unless-stopped
    user: "1001:1001"                # <-- specify user here
    user_add:
      - "1002" # media
    ports:
      - "8080:10801"
    volumes:
      - /home/docker/volumes/stump/config:/config
      - /data/media/books:/books
    # environment:
    #   - PUID=1001
    #   - PGID=1001
    env_file:
      - stack.env
```

**Additional context**

Currently setting user with "user: 1000:1000" breaks for me.
