### ISSUE TITLE
[BUG] Container fails with "Failed to parse provided PORT_KEY"

### ISSUE THREAD

**Issue by blinky-z** [stumpapp/stump#563]
## Description of the Bug

When running Stump (containerized) the application fails with the following message - full log:
```text
│ Adding group stump with gid 1000                                                                                    
│ Adding user stump with uid 1000                                                                                      
│ Setting timezone to Europe/Moscow                                                                                    
│ Failed to parse provided PORT_KEY: invalid digit found in string                                            
│ Error: InvalidConfig("Failed to initialize Stump core: invalid digit found in string")
```

I tried different image tags - latest, nightly, 0.0.9 - same issue everywhere.

## Expected Behavior

The application doesn't fail.

## To Reproduce

Run the container image.

**Environment:**

- OS: Linux

**Build Details:**

- Version: 0.0.9, nightly, latest
- Docker: yes

**Comment by aaronleopold** [comment]
What is the value you provided for the port?

**Comment by blinky-z** [comment]
I didn't provide any env vars othen than PUID, GUID, and TZ

**Comment by aaronleopold** [comment]
Can you share the contents of the `Stump.toml` file?

**Comment by blinky-z** [comment]
I don't have this file either. The local folder I mapped to /config inside the container is currently empty.

**Comment by blinky-z** [comment]
Here's the full k8s spec if that'll be helpful:
```yaml
{{- if .Values.services.stump.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.stump.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.stump.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.stump.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.stump.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.stump.name }}
    spec:
      containers:
        - name: stump
          image: "{{ .Values.services.stump.image.repository }}:{{ .Values.services.stump.image.tag }}"
          imagePullPolicy: {{ .Values.services.stump.image.pullPolicy }}
          env:
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 10801
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /data
      volumes:
        - name: config
          hostPath:
            path: "{{ .Values.services.stump.config }}"
            type: Directory
        - name: library
          hostPath:
            path: "{{ .Values.services.stump.library }}"
            type: Directory
{{- end }}
```

**Comment by aaronleopold** [comment]
I don't run k8s myself, so I won't be able to do an exact reproduction right away. I can say that spinning up a container outside k8s on my machine doesn't present any issue, even starting fresh (i.e., deleting all my configs in the mapped directory).

The error suggests that there is an environment variable for `STUMP_PORT` set which contains an invalid character. The Dockerfile does set this to `10801` [by default](https://github.com/stumpapp/stump/blob/main/docker/Dockerfile#L103).

Could you try defining it manually in the `env` section of your spec and report back what happens? Does a different configuration error occur? This reminds me of https://github.com/stumpapp/stump/issues/236

**Comment by blinky-z** [comment]
Thanks so much mate, that helped.

To anyone stumbling upon this issue, please add the `STUMP_PORT` env var manually to your container:
```yaml
      containers:
        - name: stump
          image: aaronleopold/stump:nightly
          env:
            # ...
            - name: STUMP_PORT
              value: "10801"
          ports:
            - name: http
              containerPort: 10801
              protocol: TCP
```
