### ISSUE TITLE
[BUG] Docker compose - addgroup: number 65536 is not in 0..60000 range

### ISSUE THREAD

**Issue by sggt** [stumpapp/stump#646]
## Description of the Bug

I written a docker compose file, with my standard docker user on that system:
```yml
services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    volumes:
      - /config:/config
      - /data:/data
    ports:
      - 10801:10801
    environment:
      - PUID=1029
      - PGID=65536
      - STUMP_CONFIG_DIR=/config
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
```
On startup I get following error message in the log:
`addgroup: number 65536 is not in 0..60000 range `

## Expected Behavior

That should be working, I never hat problems with that GID. Why this low limit?

**Build Details:**

- Version: [0.0.10]
- Docker: [yes]
